# ************************************ Grammar for SINHALA LANGUAGE ***************************************************

## LP   - උත්තම පුරුෂ (THIRD-PERSON)
## MP   - මධයම පුරුෂ (MIDDLE-PERSON)
## FP   - ප්‍රථම පුරුෂ (FIRST-PERSON)
## SIN  - ඒකවචන (SINGULAR)
## PLU  - බහුවචන (PLURAL)
## MAL  - පුරුෂ ලිංග (MALE)
## FEM  - ස්ත්‍රී ලිංග (FEMALE)
## PRES - වර්තමාන කාල (PRESENT TENSE)
## PAS  - අතීත කාල (PAST TENSE)
## FUT  - අනාගත කාල (FUTURE TENSE)
## NN

Rules = [
  {'NP_LP_SIN':[ 'මම']},
  {'NP_LP_SIN':[ 'මට' ]},
  {'NP_LP_SIN':[ 'ළමයා' ]},
  {'NP_LP_SIN':[ 'දරුවා' ]},
  {'NP_LP_PLU': ['අපි']},
  {'NP_LP_PLU': ['අපේ']},
  {'NP_LP_PLU': ['අප']},
  {'NP_LP_PLU': ['දරුවෝ']},
  {'NP_MP_SIN' :[ 'නුබ']},
  {'NP_MP_SIN' :[ 'ඔබ']},
  {'NP_MP_SIN' :['තෝ']},
  {'NP_MP_PLU' :[ 'නුබලා']},
  {'NP_MP_PLU' :[ 'ඔබලා']},
  {'NP_MP_PLU' :['තොපි']},
  {'NP_FP_SIN':[ 'ගොනා']},
  {'NP_FP_SIN':[ 'ඔවුහු']},
  {'NP_FP_SIN':[ 'දාසයා']},
  {'NP_FP_SIN':[ 'ඔහු']},
  {'NP_FP_SIN':[ 'නළුවා']},
  {'NP_FP_SIN':[ 'අජිත්']},
  {'NP_FP_SIN':[ 'කොටියා']},
  {'NP_FP_SIN':[ 'බල්ලා']},
  {'NP_FP_SIN':[ 'ජනරාල්වරයා']},
  {'NP_FP_SIN':['ඔහුගේ']},
  {'NP_FP_SIN':['අම්මා']},
  {'NP_FP_SIN':['ඈ']},
  {'NP_FP_SIN':['නිළිය']},
  {'NP_FP_SIN':['ඇයට']},
  {'NP_FP_SIN':['නැන්දා']},
  {'NP_FP_SIN':['ඇය']},
  {'NP_FP_SIN':['නංගී']},
  {'NP_FP_SIN':['ඇයගේ']},
  {'NP_FP_SIN':['උපාසිකාව']},
  {'NP_FP_SIN':['ස්ත්‍රියට']},
  {'NP_FP_SIN':['කිරිල්ල']},
  {'NP_FP_SIN':['සහෝදරියක්']},
  {'NP_FP_SIN':['නන්දා']},
  {'NP_FP_SIN':['ඇයව']},
  {'NP_FP_SIN':['අශිනි']},
  {'NP_FP_PLU': ['පිරිමි']},
  {'NP_FP_PLU': ['ගොවීහු']},
  {'NP_FP_PLU': ['ඇත්තු']},
  {'NP_FP_PLU': ['තරුණයෝ']},
  {'NP_FP_PLU': ['ඔවුන්']},
  {'NP_FP_PLU': ['ගවයන්']},
  {'NP_FP_PLU': ['ගැහැනු']},
  {'VP_LP_SIN_PAS |Last Person Singular Past Tense':['කෑවෝය']},
  {'VP_LP_SIN_PAS |Last Person Singular Past Tense':['සෑදුවෙමි']},
  {'VP_LP_SIN_PAS |Last Person Singular Past Tense':['කැඩුවෙමි']},
  {'VP_LP_SIN_PAS |Last Person Singular Past Tense':['කමි']},
  {'VP_LP_SIN_PAS |Last Person Singular Past Tense':['දුටුවෙමි']},
  {'VP_LP_SIN_PAS |Last Person Singular Past Tense':['ගියෙමි']},
  {'VP_LP_SIN_PAS |Last Person Singular Past Tense':['ලීවෙමි']},
  {'VP_LP_SIN_PAS |Last Person Singular Past Tense':['කළෙමි']},
  {'VP_LP_SIN_PAS |Last Person Singular Past Tense':['නැරඹුවෙමි']},
  {'VP_LP_SIN_PAS |Last Person Singular Past Tense':['යැව්වෙමි']},
  {'VP_LP_SIN_PRES | Last person Singular Present Tense': ['සාදමි']},
  {'VP_LP_SIN_PRES | Last person Singular Present Tense': ['යමි']},
  {'VP_LP_SIN_PRES | Last person Singular Present Tense': ['ලියමි']},
  {'VP_LP_SIN_PRES | Last person Singular Present Tense': ['කරමි']},
  {'VP_LP_SIN_FUT | Last Person Singular Future Tense':['යන්නෙමි']},
  {'VP_LP_SIN_FUT | Last Person Singular Future Tense':['කරන්නෙමි']},
  {'VP_LP_SIN_FUT | Last Person Singular Future Tense':['සාදන්නෙමි']},
  {'VP_LP_SIN_FUT | Last Person Singular Future Tense':['ලියන්නෙමි']},
  {'VP_LP_PLU_PAS| Last Person Plural Past Tense': ['ගියෙමු']},
  {'VP_LP_PLU_PAS| Last Person Plural Past Tense': ['කළෙමු']},
  {'VP_LP_PLU_PAS| Last Person Plural Past Tense': ['සෑදුවෙමු']},
  {'VP_LP_PLU_PAS| Last Person Plural Past Tense': ['නැරඹුවෙමු']},
  {'VP_LP_PLU_PAS| Last Person Plural Past Tense': ['ලීවෙමු']},
  {'VP_LP_PLU_PAS| Last Person Plural Past Tense': ['සෑදුවෙමු']},
  {'VP_LP_PLU_PRES | Last Person Plural Present Tense':['කමු']},
  {'VP_LP_PLU_PRES | Last Person Plural Present Tense':['යමු']},
  {'VP_LP_PLU_PRES | Last Person Plural Present Tense':['කරමු']},
  {'VP_LP_PLU_PRES | Last Person Plural Present Tense':['සාදමු']},
  {'VP_LP_PLU_PRES | Last Person Plural Present Tense':['කඩමු']},
  {'VP_LP_PLU_PRES | Last Person Plural Present Tense':['අසමු']},
  {'VP_LP_PLU_PRES | Last Person Plural Present Tense':['ලියමු']},
  {'VP_LP_PLU_PRES | Last Person Plural Present Tense':['දෙමු']},
  {'VP_LP_PLU_PRES | Last Person Plural Present Tense':['තේරුම්ගනිමු']},
  {'VP_LP_PLU_FUT |Last Person Plural Future Tense ':['කරන්නෙමු']},
  {'VP_LP_PLU_FUT |Last Person Plural Future Tense ':['සාදන්නෙමු']},
  {'VP_LP_PLU_FUT |Last Person Plural Future Tense ':['කැඩුවෙමු']},
  {'VP_LP_PLU_FUT |Last Person Plural Future Tense ':['ලියන්නෙමු']},
  {'VP_LP_PLU_FUT |Last Person Plural Future Tense ':['ඉඳිමු']},
  {'VP_MP_SIN_PAS | Middle Person Singular Past Tense':['ගියෙහි']},
  {'VP_MP_SIN_PAS | Middle Person Singular Past Tense':['ගඟෙහි']},
  {'VP_MP_SIN_PAS | Middle Person Singular Past Tense':['සෑදුවෙහි']},
  {'VP_MP_SIN_PAS | Middle Person Singular Past Tense':['කලෙහි']},
  {'VP_MP_SIN_PRES | Middle Person Singular Present Tense':['බලහි']},
  {'VP_MP_SIN_PRES | Middle Person Singular Present Tense':['සාදහි']},
  {'VP_MP_SIN_PRES | Middle Person Singular Present Tense':['කරහි']},
  {'VP_MP_SIN_PRES | Middle Person Singular Present Tense':['යහි']},
  {'VP_MP_SIN_FUT | Middle Person Singular Future Tense':['යන්නෙහි']},
  {'VP_MP_SIN_FUT | Middle Person Singular Future Tense':['කරන්නෙහි']},
  {'VP_MP_SIN_FUT | Middle Person Singular Future Tense':['සාදන්නෙහි']},
  {'VP_MP_SIN_FUT | Middle Person Singular Future Tense':['කූඩුවෙහි']},
  {'VP_MP_SIN_FUT | Middle Person Singular Future Tense':['බලන්නෙහි']},
  {'VP_MP_PLU_PAS |  Middle Person Plural Past Tense' :['ගැයුවෙහු']},
  {'VP_MP_PLU_PAS |  Middle Person Plural Past Tense' :['එවූ']},
  {'VP_MP_PLU_PAS |  Middle Person Plural Past Tense' :['කෑවෙහු']},
  {'VP_MP_PLU_PAS |  Middle Person Plural Past Tense' :['බැලුවෙහු']},
  {'VP_MP_PLU_PAS |  Middle Person Plural Past Tense' :['සෑදුවෙහු']},
  {'VP_MP_PLU_PAS |  Middle Person Plural Past Tense' :['කැඩුවෙහු']},
  {'VP_MP_PLU_PAS |  Middle Person Plural Past Tense' :['කලෙහු']},
  {'VP_MP_PLU_PAS |  Middle Person Plural Past Tense' :['ගියෙහු']},
  {'VP_MP_PLU_PRES |  Middle Person Plural Past Tense' :['බලහු']},
  {'VP_MP_PLU_PRES |  Middle Person Plural Present Tense': ['යහු']},
  {'VP_MP_PLU_PRES |  Middle Person Plural Present Tense': ['කරහු']},
  {'VP_MP_PLU_PRES |  Middle Person Plural Present Tense': ['සාදහු']},
  {'VP_MP_PLU_FUT |  Middle Person Plural Future Tense': ['යන්නෙහු']},
  {'VP_MP_PLU_FUT |  Middle Person Plural Future Tense': ['කරන්නෙහු']},
  {'VP_MP_PLU_FUT |  Middle Person Plural Future Tense': ['සාදන්නෙහු']},
  {'VP_FP_SIN_PRES_MAL' :['යයි']},
  {'VP_FP_SIN_PRES_MAL' :['කරයි']},
  {'VP_FP_SIN_PRES_MAL' :['වැටෙයි']},
  {'VP_FP_SIN_PRES_MAL' :['සාදයි']},
  {'VP_FP_SIN_PRES_MAL' :['කපයි']},
  {'VP_FP_SIN_PRES_MAL' :['සිටියි']},
  {'VP_FP_SIN_PRES_MAL' :['ආදරෙයි']},
  {'VP_FP_SIN_PRES_MAL' :['නාදවෙයි']},
  {'VP_FP_SIN_PRES_MAL' :['හඬයි']},
  {'VP_FP_SIN_PRES_MAL' :['හිඳියි']},
  {'VP_FP_SIN_PRES_MAL' :['කඩයි']},
  {'VP_FP_SIN_PRES_MAL' :['කැඳවයි']},
  {'VP_FP_SIN_PRES_MAL' :['කියයි']},
  {'VP_FP_SIN_PRES_MAL' :['පාවෙයි']},
  {'VP_FP_SIN_PRES_MAL' :['ගෙනෙයි']},
  {'VP_FP_SIN_PRES_MAL' :['ලගියි']},
  {'VP_FP_SIN_PRES_MAL' :['ඉගිළෙයි']},
  {'VP_FP_SIN_PRES_MAL' :['හාරයි']},
  {'VP_FP_SIN_PRES_MAL' :['උයයි']},
  {'VP_FP_SIN_PRES_MAL' :['ලියයි']},
  {'VP_FP_SIN_PRES_MAL' :['දුවයි']},
  {'VP_FP_SIN_PRES_MAL' :['රවටයි']},
  {'VP_FP_SIN_PRES_MAL' :['නඟී']},
  {'VP_FP_SIN_PRES_MAL' :['කරයි']},
  {'VP_FP_SIN_FUT_MAL' :['කරන්නේය']},
  {'VP_FP_SIN_FUT_MAL' :['ලියන්නේය']},
  {'VP_FP_SIN_FUT_MAL' :['ලිව්වේය']},
  {'VP_FP_SIN_FUT_MAL' :['විමසුවේය']},
  {'VP_FP_SIN_FUT_MAL' :['ගැයුවේය']},
  {'VP_FP_SIN_PAS_FEM' :['ගියාය']},
  {'VP_FP_SIN_PAS_FEM' :['කලාය']},
  {'VP_FP_SIN_PAS_FEM' :['සෑදුවාය']},
  {'VP_FP_SIN_PAS_FEM' :['කෑවාය']},
  {'VP_FP_SIN_PAS_FEM' :['ඉව්වාය']},
  {'VP_FP_SIN_PAS_FEM' :['බිව්වාය']},
  {'VP_FP_SIN_PAS_FEM' :['දුටුවාය']},
  {'VP_FP_SIN_PAS_FEM' :['වැන්දාය']},
  {'VP_FP_SIN_PAS_FEM' :['ලිව්වාය']},
  {'VP_FP_SIN_PAS_FEM' :['ඉගිළුණාය']},
  {'VP_FP_SIN_PAS_FEM' :['කීවාය']},
  {'VP_FP_SIN_PAS_FEM' :['කීවාය']},
  {'VP_FP_SIN_PAS_FEM' :['ඉගිළුණාය']},
  {'VP_FP_SIN_PAS_FEM' :['වැන්දාය']},
  {'VP_FP_SIN_PAS_FEM' :['දුටුවාය']},
  {'VP_FP_SIN_PAS_FEM' :['කලාය']},
  {'VP_FP_SIN_PAS_FEM' :['සෑදුවාය']},
  {'VP_FP_SIN_PAS_FEM' :['ඉව්වාය']},
  {'VP_FP_SIN_PAS_FEM' :['බිව්වාය']},
  {'VP_FP_SIN_PAS_FEM':['මගහැරියාය']},
  {'VP_FP_SIN_PRES_FEM' : ['දෙන්නීය']},
  {'VP_FP_SIN_PRES_FEM' : ['නටන්නීය']},
  {'VP_FP_SIN_PRES_FEM' : ['මහන්නීය']},
  {'VP_FP_SIN_PRES_FEM' : ['සාදන්නීය']},
  {'VP_FP_SIN_PRES_FEM' : ['කරන්නීය']},
  {'VP_FP_SIN_PRES_FEM' : ['යන්නීය']},
  {'VP_FP_PLU_PAS': ['ගියෝය']},
  {'VP_FP_PLU_PAS': ['කලෝය']},
  {'VP_FP_PLU_PAS': ['සෑදුවෝය']},
  {'VP_FP_PLU_PAS': ['කෑවෝය']},
  {'VP_FP_SIN_PAS_MAL': ['කළහ']},
  {'VP_FP_SIN_PAS_MAL': ['ගියහ']},
  {'VP_FP_PLU_PAS': ['කියෙව්වෝය']},
  {'VP_FP_PLU_PAS': ['මගහැරියෝය']},
  {'VP_FP_PLU_PAS': ['කළෝය']},
  {'VP_FP_PLU_PRES' :['යති']},
  {'VP_FP_PLU_PRES' :['ගනිති']},
  {'VP_FP_PLU_PRES' :['එති']},
  {'VP_FP_PLU_PRES' :['කති']},
  {'VP_FP_PLU_PRES' :['යන්නෝය']},
  {'VP_FP_PLU_PRES' :['කරති']},
  {'VP_FP_PLU_PRES' :['කරන්නෝය']},
  {'VP_FP_PLU_PRES' :['උගනිති']},
  {'VP_FP_PLU_PRES' :['සාදති']},
  {'VP_FP_PLU_PRES' :['කඩති']},
  {'VP_FP_PLU_PRES' :['කොටති']},
  {'VP_FP_PLU_PRES' :['කියති']},
  {'VP_FP_PLU_PRES' :['බසිති']},
  {'VP_FP_PLU_PRES' :['සිටිති']},
  {'VP_FP_PLU_PRES' :['පදිති']},
  {'VP_FP_PLU_PRES' :['කියන්නෝය']},
  {'VP_FP_PLU_PRES' :['මරති']},
  {'VP_FP_PLU_PRES' :['වන්නෝය']},
  {'OP':['කෑම']},
  {'OP':['වාදනය']},
  {'OP':['තොරණ']},
  {'OP':['කොළඹ']},
  {'OP':['සෙල්ලම්']},
  {'OP':['බලන්න']},
  {'OP':['බත්']},
  {'OP':['ඒ']},
  {'OP':['බබා']},
  {'OP':['පරෙවියා']},
  {'OP':['හුස්ම']},
  {'OP':['දිගටම']},
  {'OP':['සුළඟට']},
  {'OP':['කතා']},
  {'OP':['එය']},
  {'OP':['නරක']},
  {'OP':['තුඹසට']},
  {'OP':['අකුරු']},
  {'OP':['මිනිසා']},
  {'OP':['තණ']},
  {'OP':['දුම්රිය']},
  {'OP':['හොරණ']},
  {'OP':['දුම්රියක']},
  {'OP':['නැගී']},
  {'OP':['ගම්පහ']},
  {'OP':['කොච්චියේ']},
  {'OP':['වේගයෙන්']},
  {'OP':['ගෙඩියක්']},
  {'OP':['ගසින්']},
  {'OP':['ගසක්']},
  {'OP':['මුල']},
  {'OP':['ගම්වැස්සෝ']},
  {'OP':['බොරුවක්']},
  {'OP':['කවි']},
  {'OP':['සර්පිනාව']},
  {'OP':['කොඩිය']},
  {'OP':['කුඹුරෙහි']},
  {'OP':['නගුල']},
  {'OP':['ඔරුව']},
  {'OP':['ඔන්චිලි']},
  {'OP':['එතැනට']},
  {'OP':['මෝඩ']},
  {'OP':['ලියුම']},
  {'OP':['ගෙදර']},
  {'OP':['එහි']},
  {'OP':['බිම']},
  {'OP':['ගීතය']},
  {'OP':['වඳුරෙක්']},
  {'OP':['පැටවුන්ට']},
  {'OP':['ගසෙහි']},
  {'OP':['බුදුන්']},
  {'OP':['සෙමෙන්']},
  {'OP':['ගමන්']},
  {'OP':['ගී']},
  {'OP':['සෙමින්']},
  {'OP':['කැළෑවට']},
  {'OP':['පන්සල්']},
  {'OP':['පන්සලට']},
  {'OP':['හිසෙහි']},
  {'OP':['උකුණෝ']},
  {'OP':['ගස']},
  {'OP':['පෙරහැර']},
  {'OP':['පාසලට']},
  {'OP':['පාසල්']},
  {'OP':['මල්']},
  {'OP':['තදින්']},
  {'OP':['ගඟට']},
  {'OP':['කබාය']},
  {'OP':['දුරකථනය']},
  {'OP':['පොත්']},
  {'OP':['ගමට']},
  {'OP':['වැඩට']},
  {'OP':['වැඩ']},
  {'OP':['කෑම']},
  {'OP':['කුඹුරු']},
  {'OP':['වතුර']},
  {'OP':['කඩේ']},
  {'OP':['විල']},
  {'OP':['විලක්']},
  {'OP':['බොරු']},
  {'OP':['දරුවන්']},
  {'OP':['ලියුමක්']},
  {'OP':['සතුටින්']},
  {'OP':['අලංකාර']},
  {'OP':['හිඟන්නාට']},
  {'OP':['සහල්']},
  {'OP':['හෙට']},
  {'OP':['ගෘහයෙහි']},
  {'OP':['බැළලියක්']},
  {'OP':['නගරයට']},
  {'OP':['බොර']},
  {'OP':['කපටියා']},
  {'OP':['ආහාර']},
  {'OP':['ගසට']},
  {'OP':['කරමලක්']},
  {'OP':['ගස්']},
  {'OP':['සතුන්']},
  {'OP':['කුඩා']},
  {'OP':['ළමයි']},
  {'OP':['ඊයේ']},
  {'OP':['බැලීමට']},
  {'OP':['යාච්ඤාා']},
  {'OP':['සැමවිටම']},
  {'OP':['මෙහි']},
  {'OP':['නොමැත']},
  {'OP':['තොරන්']},
  {'OP':['නැමදීමට']},
  {'OP':['උදෑසනින්']},
  {'OP':['වේදිකාවේ']},
  {'OP':['අලන්කාර']},
  {'OP':['නර්ථන']}
]


